name: shell
dependencies:
  js: any
  react: ^5.1.0
  over_react: ^3.1.0

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_test:
  build_web_compilers:

dependency_overrides:
  micro_sdk:
    path: ../micro_sdk