name: reactor_experience
dependencies:
  reactor: ^0.1.0
dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:

dependency_overrides:
  micro_sdk:
    path: ../../
  shared_events:
    path: ../shared_events/
